console.log('Hello World ')
console.log('ملاعلاب ابحرم  ')
console.log('Hola Mundo  ')
console.log('Bonjour le monde  ')
console.log('Selam Dünya  ')
console.log('こんにちは世界 ')
console.log('你好世界  ')
console.log('یلو ورلڈ  ')
console.log('Olá Mundo  ')
console.log('नमस्ते दुनिया ')